name: Run data export

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openresty/openresty:alpine-fat

    outputs:
      changes_detected: ${{ steps.autocommit.outputs.changes_detected }}

    steps:
      - run: apk add --no-cache git
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          path: RePoE
      - name: checkout pob
        uses: actions/checkout@v4.2.2
        with:
          repository: PathOfBuildingCommunity/PathOfBuilding
          path: PathOfBuilding
      - name: checkout pob2
        uses: actions/checkout@v4.2.2
        with:
          repository: PathOfBuildingCommunity/PathOfBuilding-PoE2
          path: PathOfBuilding2
      - name: install json
        run: luarocks install dkjson
      - name: create poe1 dirs
        run: find PathOfBuilding/src/Data/ -type d | sed 's|PathOfBuilding/src/Data|RePoE/pob-data/poe1/|g' | while read DIR; do mkdir -p $DIR; done
      - name: run poe1 lua
        run: find PathOfBuilding/src/Data/ -name '*.lua' -exec luajit RePoE/lua/Generate.lua '{}' RePoE/pob-data/poe1/ \;
      - name: create poe2 dirs
        run: find PathOfBuilding2/src/Data/ -type d | sed 's|PathOfBuilding2/src/Data|RePoE/pob-data/poe2/|g' | while read DIR; do mkdir -p $DIR; done
      - name: run poe2 lua
        run: find PathOfBuilding2/src/Data/ -name '*.lua' -exec luajit RePoE/lua/Generate.lua '{}' RePoE/pob-data/poe2/ \;
      - name: commit changes
        id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v5.2.0
        with:
          repository: RePoE
      - name: generate index.html
        run: find pob-data -type d -exec tree {} --dirsfirst -F "PoB data export" -I 'index.html|schema_doc*' --noreport --charset utf-8 -o {}/index.html \;
        working-directory: RePoE
      - name: upload gh-pages artifact
        if: github.event_name == 'workflow_dispatch' || steps.autocommit.outputs.changes_detected == 'true'
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: RePoE/pob-data/

  deploy:
    runs-on: ubuntu-latest

    needs: build
    if: github.event_name == 'workflow_dispatch' || needs.build.outputs.changes_detected == 'true'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy gh-pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
